import {
  faChevronLeft,
  faChevronRight,
  faCircleInfo,
  faDownload,
  faEnvelope,
  faFilter,
  faPen,
  faPlus,
  faRotateRight,
  faSearch,
  faSliders,
  faSort,
  faSortDown,
  faSortUp,
  faTrash,
  faTriangleExclamation,
  faEllipsisVertical,
  faLock,
  faKey,
  faUserShield,
  faRightToBracket,
  faArrowUpRightFromSquare,
  faHome,
  faUsers,
  faUserTag,
  faCubes,
  faFingerprint,
  faShieldHalved,
  faLaptop,
  faFileShield,
  faDesktop,
  faChartLine,
  faClipboardList,
  faGear,
  faUserCircle,
  faChevronDown,
  faChevronUp,
  faXmark,
  faClone,
  faTableCellsLarge,
  faTableList
} from '@fortawesome/free-solid-svg-icons';

export const APP_ICONS = {
  home: faHome,
  users: faUsers,
  roles: faUserTag,
  modules: faCubes,
  permission: faFingerprint,
  security: faShieldHalved,
  sessions: faLaptop,
  policies: faFileShield,
  audit: faClipboardList,
  signin: faRightToBracket,
  device: faDesktop,
  chart: faChartLine,
  settings: faGear,
  profile: faUserCircle,
  create: faPlus,
  edit: faPen,
  delete: faTrash,
  search: faSearch,
  filter: faFilter,
  chevronRight: faChevronRight,
  chevronLeft: faChevronLeft,
  chevronDown: faChevronDown,
  chevronUp: faChevronUp,
  circleInfo: faCircleInfo,
  info: faTriangleExclamation,
  refresh: faRotateRight,
  export: faDownload,
  gridSettings: faSliders,
  sort: faSort,
  sortAsc: faSortUp,
  sortDesc: faSortDown,
  more: faEllipsisVertical,
  lock: faLock,
  key: faKey,
  userShield:faUserShield,
  detailView: faArrowUpRightFromSquare,
  email: faEnvelope,
  close: faXmark,
  duplicate: faClone,
  densityComfortable: faTableCellsLarge,
  densityCompact: faTableList,
} as const;
